# Generated by Django 4.1.4 on 2023-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_external',
            field=models.URLField(blank=True),
        ),
    ]
